image: "python:2.7"

before_script:
  - export PIP_CACHE_DIR=".pip-cache"
  - virtualenv env
  - source env/bin/activate
  - pip install plank
  - plank install_requirements

cache:
  paths:
    - .pip-cache

test:
  script:
    - plank tests
